backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow
display_url: https://www.wargabantuwarga.com

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Configuration"
        file: "_content/site-config.json"
        description: "General site settings"
        fields:
          - label: "Site name"
            name: "site_name"
            widget: "string"
            hint: "The main name of the website, e.g., **Warga Bantu Warga** | Informasi Faskes & Alkes untuk COVID-19"
          - label: "Site tagline"
            name: "site_tagline"
            widget: "string"
            hint: "The tagline to accompany the name, e.g., Warga Bantu Warga | **Informasi Faskes & Alkes untuk COVID-19**"
          - label: "Site description"
            name: "site_description"
            widget: "string"
            hint: "The description of the site to be shown in the URL previews on Google, Facebook, Twitter, WhatsApp, etc."
          - label: "Site URL"
            name: "site_url"
            widget: "string"
            hint: "The canonical URL of the website, complete with the protocol (e.g. `https://`) and **without** trailing slash (`/`)."
  - name: "home_page"
    label: "Home Page"
    delete: false
    preview_path: ""
    files:
      - name: "home_page"
        label: "Home Page"
        file: "_content/home-page.md"
        fields:
          - {
              label: "Last updated time",
              name: "last_updated_time",
              widget: "datetime",
              hint: "Last updated time",
            }
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              hint: "Page body",
            }
          - {
              label: "Banner Image",
              name: "home_banner_image_path",
              widget: "string",
              required: false,
              hint: "Cloudinary image path, eg. `v12345/my_file.png`",
            }
  - name: "isoman_page"
    label: "Isoman Page"
    delete: false
    preview_path: "isolasi-mandiri"
    files:
      - name: "isoman_page"
        label: "Isoman Page"
        file: "_content/isoman-page.json"
        fields:
          - name: "isoman_contents"
            label: "Isoman Contents"
            widget: list
            fields:
              - { label: "Category", name: "category", widget: "string" }
              - { label: "Category Title", name: "title", widget: "string" }
              - {
                  label: "Category Description",
                  name: "description",
                  widget: "text",
                  required: false,
                }
              - label: "Links List"
                name: links
                widget: list
                fields:
                  - { label: "Link Title", name: "title", widget: "string" }
                  - { label: "Link URL", name: "url", widget: "string" }
